eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    prefer-ip-address : true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always




spring:
  cloud:
    discovery:
      enabled : true
    config:
      enabled : true
