spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ayman
    url: jdbc:postgresql://localhost:5431/ayman
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: create-drop
