spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5432/ayman
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop

demand:
  params:
    expirationTimeMs: 36000000
    generationAlgorithm: HS512
  security:
      jwtSecret: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0Nzg5MDEyMzQ1Njc4OTAxMjM0NTY"