spring:
  mail:
    username: 'ay.elhamiani@gmail.com'
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: 'yndk ozcw ygmu okua'

twilio:
  trial_number: ''
  account_sid: ''
  auth_token: ''