spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: 'ay.elhamiani@gmail.com'
    password: 'rekp xulg larr kzuj'
    port: '587'
    default-encoding: UTF-8
    from: 'Agence Direct <ay.elhamiani@gmail.com>'
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification_service

twilio:
  trial_number: ''
  account_sid: ''
  auth_token: ''