spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://postgres:5431/postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


otp:
  params:
    retryWaitTimeInMinutes: 30
    maxGenerationAttempts: 3
    otpLengthChar: 6
    generationAlgorithm: SHA-256
    expiryOtpTimeInMinutes: 15
    maxAttemptsBeforeExpiry: 3