spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://postgres:5432/postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop